# Generated by Django 5.2.6 on 2025-09-23 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao_curta', models.TextField(help_text='Descrição que aparece na miniatura do curso.')),
                ('imagem', models.ImageField(upload_to='cursos/imagens/')),
            ],
        ),
    ]
