# Generated by Django 5.2.6 on 2025-09-29 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_curso'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='data_inicio',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='curso',
            name='imagem',
            field=models.ImageField(upload_to='cursos/'),
        ),
    ]
