# Generated by Django 5.2.6 on 2025-09-30 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_curso_data_inicio_alter_curso_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='descricao_completa',
            field=models.TextField(blank=True),
        ),
    ]
